version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: gone-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_TCP_PORT: 3308
    ports:
      - "${DB_PORT}:3308"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gone_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Gone
    restart: always
    ports:
      - "${APP_PORT}:2000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./:/app
      - /app/tmp
    depends_on:
      - db
    networks:
      - gone_network

volumes:
  db_data:

networks:
  gone_network:
    driver: bridge
