version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gone-spring
    restart: always
    ports:
      - "${APP_PORT}:2001"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
      - /app/tmp
    networks:
      - gone_network

networks:
  gone_network:
    driver: bridge
