apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualservers.k8s.nginx.org
spec:
  group: k8s.nginx.org
  names:
    plural: virtualservers
    singular: virtualserver
    kind: VirtualServer
    shortNames:
      - vs
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
                upstreams:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      service:
                        type: string
                      port:
                        type: integer
                routes:
                  type: array
                  items:
                    type: object
                    properties:
                      path:
                        type: string
                      action:
                        type: object
                        properties:
                          pass:
                            type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualserverroutes.k8s.nginx.org
spec:
  group: k8s.nginx.org
  names:
    plural: virtualserverroutes
    singular: virtualserverroute
    kind: VirtualServerRoute
    shortNames:
      - vsr
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                host:
                  type: string
                upstreams:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      service:
                        type: string
                      port:
                        type: integer
                subroutes:
                  type: array
                  items:
                    type: object
                    properties:
                      path:
                        type: string
                      action:
                        type: object
                        properties:
                          pass:
                            type: string
